version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Fluffy-Bean/TastyBites"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["browser"]

[[transformers]]
name = "prettier"